"""em email nullable false

Revision ID: 310481f20b7a
Revises: 3fcfbb5fceaf
Create Date: 2025-06-19 12:50:23.162687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '310481f20b7a'
down_revision = '3fcfbb5fceaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive_members', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive_members', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)

    # ### end Alembic commands ###
