"""hour and address to activitiy

Revision ID: 58920c5e73ef
Revises: 2bae3a17a134
Create Date: 2025-07-20 19:21:12.896098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58920c5e73ef'
down_revision = '2bae3a17a134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('meeting_id',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['id'])
        batch_op.create_foreign_key(None, 'meetings', ['meeting_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('meeting_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('hour')

    # ### end Alembic commands ###
