"""Add passwords fields

Revision ID: 77634fa99a66
Revises: 048b0341fc08
Create Date: 2025-07-10 15:53:13.681088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77634fa99a66'
down_revision = '048b0341fc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executive_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('executive_members', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
