"""update content

Revision ID: 7880b97a2801
Revises: 68bda25bb5eb
Create Date: 2025-07-15 09:03:13.402253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7880b97a2801'
down_revision = '68bda25bb5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=200), nullable=True))
        batch_op.drop_column('title')

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=200), nullable=True))
        batch_op.drop_column('title')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fontSize', sa.Float(), nullable=True))

    with op.batch_alter_table('task_repartition_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=200), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_repartition_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('filename')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('fontSize')
        batch_op.drop_column('organization')

    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('filename')

    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
