"""replace datetime to date

Revision ID: 9e9306e17f68
Revises: e9b10721c54f
Create Date: 2025-06-19 13:57:54.933465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e9306e17f68'
down_revision = 'e9b10721c54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('end',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('remembered',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('end',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('remembered',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('end',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
