"""change quotes text

Revision ID: a45f137f03f7
Revises: 58920c5e73ef
Create Date: 2025-07-20 21:53:27.836384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a45f137f03f7'
down_revision = '58920c5e73ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=400),
               nullable=True)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
