"""add content db

Revision ID: fc38717431e2
Revises: 77634fa99a66
Create Date: 2025-07-11 16:29:12.367085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc38717431e2'
down_revision = '77634fa99a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_repartition_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('file', sa.String(length=400), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_repartition_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=400), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))

    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('author')

    with op.batch_alter_table('annual_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('visible')
        batch_op.drop_column('title')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('author')

    op.drop_table('task_repartition_text')
    op.drop_table('task_repartition_file')
    # ### end Alembic commands ###
